import { Archetype, Badge } from './types';

export const ARCHETYPES: Record<string, Archetype> = {
  // Base 2x2 Grid
  hishabi: {
    id: 'hishabi',
    name: 'The Hishabi',
    banglaName: 'হিসাবী',
    tagline: 'Every taka has a job before it even arrives.',
    banglaTagline: 'আসার আগেই প্রতি টাকার হিসাব পাকা।',
    blurb: 'You budget, you track, and a countdown timer has never once rattled you. Certified হিসাবী — the friend who always knows exactly what is left before month-end.',
    shareLine: "I'm The Hishabi 🧮",
    accentColor: '#10B981',
    imagePath: '/characters/hishabi.jpg',
    tier: 'base',
    rarity: 'Common',
  },
  'plan-then-panic': {
    id: 'plan-then-panic',
    name: 'Plan-Then-Panic',
    banglaName: 'প্ল্যান-দেন-প্যানিক',
    tagline: 'Made a budget. Broke it by day three. Still proud of the spreadsheet.',
    banglaTagline: 'বাজেট হলো। তিন দিনে ভাঙল। স্প্রেডশিটটা তবুও প্রিয়।',
    blurb: 'The intention is genuine. The planning is real. And then Daraz sends a notification at the exact wrong moment and the spreadsheet becomes a historical document.',
    shareLine: "I'm Plan-Then-Panic 📊💥",
    accentColor: '#F59E0B',
    imagePath: '/characters/plan-then-panic.jpg',
    tier: 'base',
    rarity: 'Common',
  },
  '2am-checkout': {
    id: '2am-checkout',
    name: 'The 2AM Checkout Warrior',
    banglaName: '২ এএম চেকআউট ওয়ারিয়র',
    tagline: 'The Daraz notification hits harder than your alarm.',
    banglaTagline: 'অ্যালার্মের চেয়ে দারাজের নোটিফিকেশন বেশি জাগায়।',
    blurb: 'No budget, no tracking, no regrets — until the delivery arrives. You buy on pure vibes and settle up with your future self, who is frankly exhausted.',
    shareLine: "I'm The 2AM Checkout Warrior 🌙🛒",
    accentColor: '#8B5CF6',
    imagePath: '/characters/2am-checkout.jpg',
    tier: 'base',
    rarity: 'Common',
  },
  'ghost-spender': {
    id: 'ghost-spender',
    name: 'The Ghost Spender',
    banglaName: 'ঘোস্ট স্পেন্ডার',
    tagline: 'Money leaves. Nobody, including you, knows how.',
    banglaTagline: 'টাকা উড়ে যায়। কীভাবে? কেউ জানে না।',
    blurb: "You're not impulsive. You don't chase sales. And yet somehow it's gone by the 20th. The money simply evaporates, and you have made peace with the mystery.",
    shareLine: "I'm The Ghost Spender 👻",
    accentColor: '#64748B',
    imagePath: '/characters/ghost-spender.jpg',
    tier: 'base',
    rarity: 'Common',
  },

  // Gate / Fallback Special Archetypes
  untouchable: {
    id: 'untouchable',
    name: 'The Untouchable',
    banglaName: 'আনটাচেবল',
    tagline: 'Daraz has never won. Not once. Not even at 2AM.',
    banglaTagline: 'দারাজ কখনো জিততে পারেনি। রাত ২টাতেও না।',
    blurb: 'Flash sales bounce off you. Countdown timers mean nothing. In an entire economy engineered around impulse, you simply declined to participate.',
    shareLine: "I'm The Untouchable 🗿",
    accentColor: '#EF4444',
    imagePath: '/characters/untouchable.jpg',
    tier: 'special',
    rarity: 'Special',
  },
  enigma: {
    id: 'enigma',
    name: 'The Enigma',
    banglaName: 'দ্য এনিগমা',
    tagline: 'You skipped the questions. Respect. We know nothing.',
    banglaTagline: 'প্রশ্ন স্কিপ করেছেন? দারুণ। আমরা কিছুই জানি না!',
    blurb: 'You gave us just enough to say thank you and absolutely nothing more. Genuinely, that is a personality type, and honestly it might be the smartest one here.',
    shareLine: "I'm The Enigma ❓",
    accentColor: '#94A3B8',
    imagePath: '/characters/enigma.jpg',
    tier: 'special',
    rarity: 'Special',
  },

  // Tier 1 Contradiction Types
  'delusional-cfo': {
    id: 'delusional-cfo',
    name: 'The Delusional CFO',
    banglaName: 'ডিলিউশনাল সিএফও',
    tagline: 'Supreme confidence. Zero evidence.',
    banglaTagline: 'আকাশছোঁয়া আত্মবিশ্বাস। পকেটের প্রমাণ শূন্য।',
    blurb: "You feel completely in control of your money, and you also run out of it every single month. Both things are true at once. We're not going to be the ones to break the illusion.",
    shareLine: "I'm The Delusional CFO 💼",
    accentColor: '#1E3A8A',
    imagePath: '/characters/delusional-cfo.jpg',
    tier: 'contradiction',
    rarity: 'Legendary',
  },
  'humble-menace': {
    id: 'humble-menace',
    name: 'The Humble Menace',
    banglaName: 'হাম্বল মেনেস',
    tagline: 'Thinks they spend less than everyone. Statistically, no.',
    banglaTagline: 'ভাবেন সবার চেয়ে কম খরচ করেন। পরিসংখ্যানে পুরো উল্টো।',
    blurb: "You're convinced you're the careful one in your friend group. Your actual answers suggest you might be the reason your friend group has a secret chat about spending.",
    shareLine: "I'm The Humble Menace 😇",
    accentColor: '#EC4899',
    imagePath: '/characters/humble-menace.jpg',
    tier: 'contradiction',
    rarity: 'Rare',
  },
  theorist: {
    id: 'theorist',
    name: 'The Theorist',
    banglaName: 'দ্য থিওরিষ্ট',
    tagline: 'Beautiful budget. Purely decorative.',
    banglaTagline: 'সুন্দর বাজেট। শুধুই প্রদর্শনের জন্য।',
    blurb: 'You make the plan. You do not consult the plan. The plan exists as an art object, admired occasionally, followed never.',
    shareLine: "I'm The Theorist 📐",
    accentColor: '#0D9488',
    imagePath: '/characters/plan-then-panic.jpg',
    tier: 'contradiction',
    rarity: 'Rare',
  },

  // Tier 2 Lifestyle Types
  'family-pillar': {
    id: 'family-pillar',
    name: 'The Family Pillar',
    banglaName: 'ফ্যামিলি পিলার',
    tagline: 'Carrying more than the budget shows.',
    banglaTagline: 'বাজেটের চেয়েও বেশি দায়িত্ব কাঁধে।',
    blurb: 'You are sending money home on one of the tightest personal budgets in this survey. Every taka you manage is doing double duty. Quietly, this is the hardest mode in the game.',
    shareLine: "I'm The Family Pillar 🛡️",
    accentColor: '#D97706',
    imagePath: '/characters/family-pillar.jpg',
    tier: 'lifestyle',
    rarity: 'Legendary',
    isDignified: true,
  },
  hustler: {
    id: 'hustler',
    name: 'The Hustler',
    banglaName: 'দ্য হাসলার',
    tagline: 'Three income streams and a 9AM class.',
    banglaTagline: 'তিনটি ইনকাম সোর্স, সাথে সকাল ৯টার ক্লাস।',
    blurb: "Tuition in the morning, freelancing at night, and something else on the side you'd rather not explain. You don't have a budget, you have an enterprise.",
    shareLine: "I'm The Hustler ⚡",
    accentColor: '#EAB308',
    imagePath: '/characters/hustler.jpg',
    tier: 'lifestyle',
    rarity: 'Rare',
  },
  'bank-of-friends': {
    id: 'bank-of-friends',
    name: 'The Bank of Friends',
    banglaName: 'ব্যাংক অফ ফ্রেন্ডস',
    tagline: "Everyone owes you. You've lost the list.",
    banglaTagline: 'সবার কাছে টাকা পান, তবে হিসাবের খাতা হারিয়ে গেছে।',
    blurb: 'You lend without records and somehow never chase anyone. Your friends love you. Your money definitely does not.',
    shareLine: "I'm The Bank of Friends 🏦",
    accentColor: '#14B8A6',
    imagePath: '/characters/bank-of-friends.jpg',
    tier: 'lifestyle',
    rarity: 'Rare',
  },
  'window-shopper': {
    id: 'window-shopper',
    name: 'The Window Shopper',
    banglaName: 'উইন্ডো শপার',
    tagline: 'Watches every sale. Buys nothing. Legend.',
    banglaTagline: 'প্রতিটি সেল দেখে, কেনে শূন্য। খাঁটি লিজেন্ড।',
    blurb: "You follow deal groups religiously and purchase nothing. You're studying the enemy. Total surveillance, zero expenditure.",
    shareLine: "I'm The Window Shopper 🔭",
    accentColor: '#38BDF8',
    imagePath: '/characters/window-shopper.jpg',
    tier: 'lifestyle',
    rarity: 'Uncommon',
  },
  'cart-monk': {
    id: 'cart-monk',
    name: 'The Cart Monk',
    banglaName: 'দ্য কার্ট মঙ্ক',
    tagline: 'Adds to cart. Waits. Wins.',
    banglaTagline: 'কার্টে যোগ করে অপেক্ষা। শেষমেশ জয়ী।',
    blurb: "You've weaponised the waiting period. Items go in the cart and simply expire there. The discipline is genuinely upsetting to the rest of us.",
    shareLine: "I'm The Cart Monk 🧘",
    accentColor: '#78716C',
    imagePath: '/characters/cart-monk.jpg',
    tier: 'lifestyle',
    rarity: 'Uncommon',
  },
  'pay-day-phenomenon': {
    id: 'pay-day-phenomenon',
    name: 'The Payday Phenomenon',
    banglaName: 'পে-ডে ফেনোমেনন',
    tagline: 'Rich for four days. Then the long silence.',
    banglaTagline: 'চার দিনের বড়লোকী, এরপর লম্বা নীরবতা।',
    blurb: "The money arrives and there is a brief golden era of treats and luxury. Then it's the 12th, and you're negotiating with yourself over rickshaw fare.",
    shareLine: "I'm The Payday Phenomenon 📉",
    accentColor: '#F43F5E',
    imagePath: '/characters/pay-day-phenomenon.jpg',
    tier: 'lifestyle',
    rarity: 'Rare',
  },
  copycat: {
    id: 'copycat',
    name: 'The Copycat',
    banglaName: 'দ্য কপিক্যাট',
    tagline: "Your friend's purchase is your shopping list.",
    banglaTagline: 'বন্ধুর কেনা জিনিসই আপনার শপিং লিস্ট।',
    blurb: "Ads don't move you at all. But the moment a classmate shows up with something new, the countdown starts. You're influenced by people, which is arguably much harder to resist.",
    shareLine: "I'm The Copycat 👀",
    accentColor: '#A855F7',
    imagePath: '/characters/copycat.jpg',
    tier: 'lifestyle',
    rarity: 'Uncommon',
  },
  'cash-purist': {
    id: 'cash-purist',
    name: 'The Cash Purist',
    banglaName: 'ক্যাশ পিউরিস্ট',
    tagline: "If it's not in the pocket, it doesn't exist.",
    banglaTagline: 'পকেটে নগদ না থাকলে সেটির কোনো অস্তিত্ব নেই।',
    blurb: 'No apps, no cards, no digital paper trail. You operate exclusively in physical notes, and your spending awareness is strictly tactile.',
    shareLine: "I'm The Cash Purist 💵",
    accentColor: '#15803D',
    imagePath: '/characters/cash-purist.jpg',
    tier: 'lifestyle',
    rarity: 'Uncommon',
  },
  survivor: {
    id: 'survivor',
    name: 'The Survivor',
    banglaName: 'দ্য সারভাইভার',
    tagline: 'The session jam took the budget with it.',
    banglaTagline: 'সেশন জট গেল, বাজেটও সাথে নিয়ে গেল।',
    blurb: 'Your financial planning has been repeatedly rearranged by forces entirely outside your control. You have adapted more times than any student budget should have to.',
    shareLine: "I'm The Survivor 🧗",
    accentColor: '#78350F',
    imagePath: '/characters/survivor.jpg',
    tier: 'lifestyle',
    rarity: 'Rare',
    isDignified: true,
  },

  // Bonus Types
  'cash-hoarder': {
    id: 'cash-hoarder',
    name: 'The Cash Hoarder',
    banglaName: 'ক্যাশ হোর্ডার',
    tagline: 'Every taka locked into the digital vault.',
    banglaTagline: 'প্রতিটি টাকা জমা থাকে গোপন সিন্দুকে।',
    blurb: 'Saving is not just a habit for you — it is an art form. You stash away the vast majority of your money and treat spending like a rare concession.',
    shareLine: "I'm The Cash Hoarder 🪙",
    accentColor: '#059669',
    imagePath: '/characters/cash-hoarder.jpg',
    tier: 'bonus',
    rarity: 'Rare',
  },
  'son-of-king': {
    id: 'son-of-king',
    name: 'The Son of King',
    banglaName: 'রাজার ব্যাটা',
    tagline: 'Royal logistics, zero financial turbulence.',
    banglaTagline: 'রাজকীয় সাপোর্ট, আর্থিক দুশ্চিন্তা শূন্য।',
    blurb: 'Expenses are handled seamlessly, logistics are managed, and financial panic is something other people experience in textbooks. Living the effortless royal campus life.',
    shareLine: "I'm The Son of King 👑",
    accentColor: '#6366F1',
    imagePath: '/characters/son-of-king.jpg',
    tier: 'bonus',
    rarity: 'Legendary',
  },
};

export const BADGES: Record<string, Badge> = {
  'safety-net': {
    id: 'safety-net',
    name: "Family's Safety Net",
    banglaName: 'ফ্যামিলির সাপোর্ট',
    icon: '🛡️',
    description: 'Supports family financially while pursuing university studies.',
  },
  'secret-shopper': {
    id: 'secret-shopper',
    name: 'Low-Key Secret Shopper',
    banglaName: 'সিক্রেট শপার',
    icon: '🤫',
    description: 'Occasionally or regularly downplays impulse buys around family.',
  },
  'emi-enthusiast': {
    id: 'emi-enthusiast',
    name: 'EMI Enthusiast',
    banglaName: 'ইএমআই ফ্যান',
    icon: '💳',
    description: 'Uses installment/BNPL options more often than planned.',
  },
};

export const ENCOURAGEMENTS = [
  {
    position: 'After Section A (University)',
    english: 'Okay, formalities done. Now the fun part.',
    bangla: 'আনুষ্ঠানিকতা শেষ। এবার আসল খেলা।',
  },
  {
    position: 'After Section B (About You)',
    english: 'Halfway to knowing yourself better than your bank statement does.',
    bangla: 'নিজেকে চেনার পথে অর্ধেক এগিয়ে গেছেন।',
  },
  {
    position: 'After Section D (Cost of Studying)',
    english: "Deep breath. The next bit is just numbers, and nobody's checking.",
    bangla: 'একটু দম নিন। সামনেরটা শুধু সংখ্যা, কেউ যাচাই করছে না।',
  },
  {
    position: 'After Section E (Household Income)',
    english: 'Money talk, survived. No judgement here — we mean that.',
    bangla: 'টাকার আলাপ পার হয়ে গেল। কেউ বিচার করছে না, সত্যি।',
  },
  {
    position: 'After Section G (Money Going Out)',
    english: 'Your wallet has been through a lot in the last two minutes.',
    bangla: 'গত দুই মিনিটে আপনার মানিব্যাগের উপর দিয়ে অনেক কিছু গেছে।',
  },
  {
    position: 'Before Section I (Buying Online)',
    english: 'Confession time. How bad is the Daraz situation, really?',
    bangla: 'সত্যি বলার সময়। দারাজের অবস্থা আসলে কতটা খারাপ?',
  },
  {
    position: 'Before Section K (Last stretch)',
    english: 'Last stretch. Your result is loading. (Not really. But almost.)',
    bangla: 'শেষ ধাপ। রেজাল্ট আসছে। (আসলে না। তবে প্রায়।)',
  },
];
